### ISSUE TITLE
Segmentation fault when trying to reset the password

### ISSUE THREAD

**Issue by centaurima** [hnojedu/HNOJ#15]
**Describe the bug**
When I press the button 'Gửi email đặt lại mật khẩu', it leads to this page:
![image](https://github.com/hnojedu/HNOJ/assets/158186760/fb9a6205-91a8-4857-ae12-d45885f2fc8d)
Hope the issue is gonna be fixed soon, since a user can only have one account for each email address.

**Comment by magnified103** [comment]
Hi, does the issue apply to [hnoj.edu.vn](hnoj.edu.vn) or this is the case with your OJ setup?
